CREATE TABLE IF NOT EXISTS `Genres`(
    `id` INT NOT NULL PRIMARY KEY,
    `name` VARCHAR(30),
    `is_active` TINYINT(1) default 1,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)